### ISSUE TITLE
[viem] `signMessage` fails when using `raw` property of `SignableMessage`

### ISSUE THREAD

**Issue by danscan** [tkhq/sdk#116]
Hey there!

I noticed that using @turnkey/viem's `signMessage` will always fail if you use the raw form of the [`SignableMessage`](https://github.com/wagmi-dev/viem/blob/7eb378d979b34376717a47e558c36878a7df2828/src/types/misc.ts#L5-L10) type.

```typescript
// succeeds
await turnkeyViemAccount.signMessage({ message: 'hello' });

// fails
await turnkeyViemAccount.signMessage({ message: { raw: stringToHex('hello') } });
await turnkeyViemAccount.signMessage({ message: { raw: hexToBytes('0x68656c6c6f') } });
```

Looks like it's due to this line, which assumes message is always a string, and casts it to `0x${string}`:
https://github.com/tkhq/sdk/blob/89d9999757e004ce6f15ca5c91ea7378774c4ee2/packages/viem/src/index.ts#L190

I believe a quick fix is to replace ```keccak256(message as `0x${string}`)``` with `hashMessage(message)`. You can import `hashMessage` from `viem` itself, and it accepts a `SignableMessage`, so it should be exactly what's needed here.

FYI Viem has a nice set of typesafe utilities, and also, as I recently found, common types like `Hex` so you don't need to type ``` `0x${string}` ``` all over :)

**Comment by andrewkmin** [comment]
Hi @danscan thanks for reporting this! Awesome catch -- we're on it: https://github.com/tkhq/sdk/pull/117

**Comment by andrewkmin** [comment]
Hey @danscan the fix has been merged + released. Will be closing this issue now - please let us know if there are any additional issues and we'd be happy to revisit. Thanks again for filing this!
