### ISSUE TITLE
Move to Node v18 given v16 is officially past its End-of-Life date

### ISSUE THREAD

**Issue by r-n-o** [tkhq/sdk#120]
See https://nodejs.org/en/blog/announcements/nodejs16-eol

When running tests with v18 I get a test failure that we'll need to fix:
```
│     TypeError: mockedFetch.mockReturnValue is not a function
│       22 |   response.json = async () => ({});
│       23 |
│     > 24 |   mockedFetch.mockReturnValue(Promise.resolve(response));
│          |               ^
│       25 |
│       26 |   await TurnkeyApi.getWhoami({
│       27 |     body: {
│       at Object.mockReturnValue (src/__tests__/request-test.ts:24:15)
```

This is probably a straightforward fix, just jotting this down here while it's fresh!

**Comment by drGrove** [comment]
Why not just go to node 20, which hits LTS status next month

**Comment by r-n-o** [comment]
Good point. We can target node 20 provided it doesn't make life difficult for SDK users (we need to be careful not to use node 20 specific features; otherwise we'd force all SDK users to upgrade to node 20+)

**Comment by r-n-o** [comment]
This now done, we're using node v18.
