### ISSUE TITLE
Viem `createAccount` is asynchronous.

### ISSUE THREAD

**Issue by mshrieve** [tkhq/sdk#349]
It would be very helpful if there were a synchronous version of the viem `createAccount` function.
`createAccount` only needs to be async if the `signWith` param is a private key ID, and there is no provided ethereum address.

I've submitted a PR here: https://github.com/tkhq/sdk/pull/348.

As I mention, I think it would be better actually if `createAccount` itself were synchronous and _required_ an ethereum address if `signWith` is not an address.  In that case we could move the logic to fetch the ethereum address associated with a private key ID to a separate, async function.

**Comment by andrewkmin** [comment]
Hey @mshrieve , thanks so much for the contribution! Greatly appreciated 💪 

Overall, in support of the approach but want to ask about this bit I saw in the PR description:

> The viem createAccount function is asynchronous, which can make a turnkey viem client tricky to use as a plug-and-play alternative to a standard viem client.

Can you elaborate on the scenario that led to this? Perhaps in a React context that does not (easily) allow for asynchronicity?

**Comment by mshrieve** [comment]
I use viem clients like this:

```
import { createPublicClient, createWalletClient, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";

import { config } from "../config";

const account = privateKeyToAccount(config.signerPrivateKey);
const chain = config.chain;
const transport = http(config.rpcUrl);

const client = {
  public: createPublicClient({
    chain,
    transport,
  }),
  wallet: createWalletClient({
    account,
    chain,
    transport,
  }),
};

export { client };
```

I can then import this wherever I need.

**Comment by andrewkmin** [comment]
Sorry this took longer than expected to ultimately close out; happy to report that this is in! Thanks so much for making the change, attribution here: https://github.com/tkhq/sdk/blob/main/packages/viem/CHANGELOG.md#minor-changes 😄
